/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jakewharton.smsmorse;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int about=0x7f050008;
        public static final int enabled=0x7f050000;
        public static final int from=0x7f050004;
        public static final int from_after=0x7f050007;
        public static final int from_before=0x7f050006;
        public static final int from_none=0x7f050005;
        public static final int from_text=0x7f050003;
        public static final int length=0x7f050002;
        public static final int length_text=0x7f050001;
        public static final int test=0x7f050009;
        public static final int test_text=0x7f05000a;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
